# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :distribute do
    firebase_app_distribution(
      app: "1:717031788374:android:3c52a8a36583f44a4650f7",
      groups: "internal-testers",
      apk_path: ENV["ANDROID_BUILD_PATH"],
      firebase_cli_path: "./node_modules/.bin/firebase",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end
end

platform :ios do
  lane :archive do

    APP_ID = "com.ngtrhieu.jumpjumpbox"
    APP_PROFILE = "match Development com.ngtrhieu.jumpjumpbox"
    TEAM_ID = "V2792QQJMU"

    KEYCHAIN_NAME = "temp_keychain"
    KEYCHAIN_PASSWORD = "temp_password"
    KEYCHAIN_PATH = "~/Library/Keychains/#{KEYCHAIN_NAME}-db"

    delete_keychain(name: KEYCHAIN_NAME) if File.exist?(File.expand_path(KEYCHAIN_PATH))
    create_keychain(
      name: KEYCHAIN_NAME,
      password: KEYCHAIN_PASSWORD,
      unlock: true,
      timeout: false,
      lock_when_sleeps: false,
      add_to_search_list: true
    )
    
    match(
      readonly: is_ci,
      keychain_name: KEYCHAIN_NAME,
      keychain_password: KEYCHAIN_PASSWORD,
      app_identifier: APP_ID,
      s3_access_key: ENV["AWS_ACCESS_KEY"],
      s3_secret_access_key: ENV["AWS_ACCESS_SECRET"],
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: File.join(ENV["BUILD_PATH"], ENV["BUILD_NAME"], "Unity-iPhone.xcodeproj"),
    )

    settings_to_override = {
      :BUNDLE_IDENTIFIER => APP_ID,
      :PROVISIONING_PROFILE_SPECIFIER => APP_PROFILE,
      :DEVELOPMENT_TEAM => TEAM_ID,
      :OTHER_CODE_SIGN_FLAGS => "--keychain=\"#{KEYCHAIN_PATH}\""
    }

    gym(
      project: File.join(ENV["BUILD_PATH"], ENV["BUILD_NAME"], "Unity-iPhone.xcodeproj"),
      scheme: "Unity-iPhone",
      output_directory: ENV["BUILD_PATH"],
      output_name: ENV["BUILD_NAME"],
      clean: true,
      xcargs: settings_to_override,
      export_options: {
        method: "development",
        provisioningProfiles: {
          APP_ID => APP_PROFILE
        }
      }
    )

    delete_keychain(
      name: "temp_keychain"
    )
  end

  lane :distribute do
    firebase_app_distribution(
      app: "1:717031788374:ios:be121905ee687dea4650f7",
      groups: "internal-testers",
      ipa_path: File.join(ENV["BUILD_PATH"], ENV["BUILD_NAME"] + ".ipa"),
      firebase_cli_path: "./node_modules/.bin/firebase",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end
end
