# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :distribute do
    firebase_app_distribution(
      app: "1:717031788374:android:3c52a8a36583f44a4650f7",
      groups: "internal-testers",
      apk_path: ENV["ANDROID_BUILD_PATH"],
      firebase_cli_path: "./node_modules/.bin/firebase",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end
end

platform :ios do
  lane :archive do

    XCODE_PROJECT_PATH = File.join(ENV["IOS_XCODE_PROJECT_PATH"], "Unity-iPhone.xcodeproj")

    KEYCHAIN_NAME = "temp_keychain"
    KEYCHAIN_PASSWORD = "temp_password"
    KEYCHAIN_PATH = "~/Library/Keychains/#{KEYCHAIN_NAME}-db"

    delete_keychain(name: KEYCHAIN_NAME) if File.exist?(File.expand_path(KEYCHAIN_PATH))
    create_keychain(
      name: KEYCHAIN_NAME,
      password: KEYCHAIN_PASSWORD,
      unlock: true,
      timeout: false,
      lock_when_sleeps: false,
      add_to_search_list: true
    )
    
    match(
      storage_mode: "s3",
    
      s3_region: ENV["AWS_REGION"],
      s3_bucket: ENV["APPLE_PROVISION_PROFILE_BUCKET"],
      s3_access_key: ENV["AWS_ACCESS_KEY"],
      s3_secret_access_key: ENV["AWS_ACCESS_SECRET"],
      
      
      app_identifier: ENV["APP_ID"],
      username: ENV["APPLE_USERNAME"],
      team_id: ENV["APPLE_TEAM_ID"],

      type: "appstore",
      readonly: is_ci,
      keychain_name: KEYCHAIN_NAME,
      keychain_password: KEYCHAIN_PASSWORD,
    )

    update_code_signing_settings(
      path: XCODE_PROJECT_PATH,
      targets: "Unity-iPhone",
      use_automatic_signing: false,
      code_sign_identity: ENV["APPLE_CODE_SIGN_IDENTITY"],
      team_id: ENV["APPLE_TEAM_ID"],
      profile_name: ENV["APPLE_PROVISION_PROFILE"]
    )

    settings_to_override = {
      :BUNDLE_IDENTIFIER => ENV["APP_ID"],
      :PROVISIONING_PROFILE_SPECIFIER => ENV["APPLE_PROVISION_PROFILE"],
      :DEVELOPMENT_TEAM => ENV["APPLE_TEAM_ID"],
    }

    gym(
      project: XCODE_PROJECT_PATH,
      scheme: "Unity-iPhone",
      output_directory: ENV["BUILD_PATH"],
      output_name: ENV["VERSIONED_BUILD_NAME"],
      clean: true,
      xcargs: settings_to_override,
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          ENV["APP_ID"] => ENV["APPLE_PROVISION_PROFILE"]
        }
      }
    )

    delete_keychain(
      name: "temp_keychain"
    )
  end

  lane :distribute do
    firebase_app_distribution(
      app: "1:717031788374:ios:be121905ee687dea4650f7",
      groups: "internal-testers",
      ipa_path: ENV["IOS_BUILD_PATH"],
      firebase_cli_path: "./node_modules/.bin/firebase",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end
end
