# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :distribute do
    firebase_app_distribution(
      app: "1:717031788374:android:3c52a8a36583f44a4650f7",
      groups: "internal-testers",
      firebase_cli_path: "./node_modules/.bin/firebase",
      apk_path: ENV["ANDROID_BUILD_PATH"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end
end

